"""adiciona coluna foto na tabela usuarios

Revision ID: d7e7bdd0c0a4
Revises: 7fea1a09cfd1
Create Date: 2026-08-28 08:14:40.021252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e7bdd0c0a4'
down_revision: Union[str, Sequence[str], None] = '7fea1a09cfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
