"""adiciona coluna titulo em quadros

Revision ID: f28cfd5ea47a
Revises: 348ea2cf4d34
Create Date: 2026-08-27 09:30:43.703998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f28cfd5ea47a'
down_revision: Union[str, Sequence[str], None] = '348ea2cf4d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quadros', sa.Column('titulo', sa.String(length=255), nullable=False))
    op.add_column('quadros', sa.Column('descricao', sa.Text(), nullable=True))
    op.add_column('quadros', sa.Column('icone', sa.String(length=50), nullable=False))
    op.add_column('quadros', sa.Column('criado_em', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.drop_column('quadros', 'nome')
    op.alter_column('usuarios', 'foto',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'foto',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.add_column('quadros', sa.Column('nome', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('quadros', 'criado_em')
    op.drop_column('quadros', 'icone')
    op.drop_column('quadros', 'descricao')
    op.drop_column('quadros', 'titulo')
    # ### end Alembic commands ###
